/*
1. CRIE UM METODO PRIVADO CHAMADO calcularDano() NA CLASSE QUE CALCULA O DANO COM BASE EM FATORES COMO resistencia E armadura
*/







/*
2. MODIFIQUE O MÉTODO sofrerDano() PARA USAR O MÉTODO calcularDano()
*/

/*
3. CRIE UMA NOVA CLASSE CHAMADA Habilidade COM UM ATRIBUTO nome: string 
*/

/*
4. MODIFIQUE A CLASSE Tributo PARA USAR UM ARRAY DE OBJETOS Habilidade INVÉS DE UM ARRAY DE STRINGS PARA HABILIDADES
*/

/*
5. ATUALIZE O MÉTODO exibirHabilidades() PARA EXIBIR OS NOMES DAS HABILIDADES
*/